FROM  alpine:3.10
LABEL Maintainer="Nguyen Chinh <nchinh.vn@gmail.com>" \
      Description="Lightweight container with Nginx 1.16 & PHP-FPM 7.3 based on Alpine Linux."
# Install packages
RUN apk --no-cache add php7 php7-fpm php7-mysqli php7-json php7-openssl php7-curl \
    php7-zlib php7-xml php7-phar php7-intl php7-dom php7-xmlreader php7-ctype php7-session \
    php7-mbstring php7-gd php7-iconv php7-xml php7-simplexml php7-xmlwriter \
    php7-tokenizer php7-fileinfo php7-pdo_mysql php7-pdo php7-exif \
    nginx supervisor curl git openssh bash nodejs npm php7-zip

RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer && \
    chown nobody:nobody /usr/local/bin/composer

RUN mkdir -p /var/www/html &&  mkdir -p /root/.ssh && mkdir -p /etc/supervisor/conf.d/

RUN echo "----COPY  nginx.conf /etc/nginx/nginx.conf " && \
    echo $'d29ya2VyX3Byb2Nlc3NlcyAgMTsKZXJyb3JfbG9nIHN0ZGVyciB3YXJuOwpwaWQgL3J1bi9uZ2lueC5waWQ7CmV2ZW50cyB7CiAgICB3b3JrZXJfY29ubmVjdGlvbnMgIDEwMjQ7Cn0KCmh0dHAgewogICAgaW5jbHVkZSAgICAgICBtaW1lLnR5cGVzOwogICAgZGVmYXVsdF90eXBlICBhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW07CgogICAgbG9nX2Zvcm1hdCAgbWFpbl90aW1lZCAgJyRyZW1vdGVfYWRkciAtICRyZW1vdGVfdXNlciBbJHRpbWVfbG9jYWxdICIkcmVxdWVzdCIgJwogICAgICAgICAgICAgICAgICAgICAgICAgICAgJyRzdGF0dXMgJGJvZHlfYnl0ZXNfc2VudCAiJGh0dHBfcmVmZXJlciIgJwogICAgICAgICAgICAgICAgICAgICAgICAgICAgJyIkaHR0cF91c2VyX2FnZW50IiAiJGh0dHBfeF9mb3J3YXJkZWRfZm9yIiAnCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAnJHJlcXVlc3RfdGltZSAkdXBzdHJlYW1fcmVzcG9uc2VfdGltZSAkcGlwZSAkdXBzdHJlYW1fY2FjaGVfc3RhdHVzJzsKCiAgICAgICAgIGFjY2Vzc19sb2cgL2Rldi9zdGRvdXQgbWFpbl90aW1lZDsKICAgICAgICAgZXJyb3JfbG9nIC9kZXYvc3RkZXJyIG5vdGljZTsKICAgICAgICAga2VlcGFsaXZlX3RpbWVvdXQgIDY1OwoKCiAgICAgICAgIHByb3h5X2Nvbm5lY3RfdGltZW91dCAgICAgICAxODA7CiAgICAgICAgIHByb3h5X3NlbmRfdGltZW91dCAgICAgICAgICAxODA7CiAgICAgICAgIHByb3h5X3JlYWRfdGltZW91dCAgICAgICAgICAxODA7CiAgICAgICAgIHNlbmRfdGltZW91dCAgICAgICAgICAgICAgICAxODA7CiAgICAgICAgIGZhc3RjZ2lfcmVhZF90aW1lb3V0ICAgICAgIDYwMHM7CgogICAgICAgICBzZXJ2ZXJfdG9rZW5zIG9mZjsKCgljbGllbnRfYm9keV9idWZmZXJfc2l6ZSAgICAgICAgICAgICAxMG07CgljbGllbnRfbWF4X2JvZHlfc2l6ZSAgICAgICAgICAgICAgICAyNTBNOwoJbGFyZ2VfY2xpZW50X2hlYWRlcl9idWZmZXJzICAgICAgMTYgNjRrOwoJY2xpZW50X2hlYWRlcl9idWZmZXJfc2l6ZSAgICAgICAgICAgNjRrOwoJcHJveHlfc2V0X2hlYWRlciBYLVJlYWwtSVAgJHJlbW90ZV9hZGRyOwoJcHJveHlfYnVmZmVyX3NpemUgICAgICAgICAgICAgICAgICAxMjhrOwoJcHJveHlfYnVmZmVycyAgICAgICAgICAgICAgICAgICAgNCAyNTZrOwoJcHJveHlfYnVzeV9idWZmZXJzX3NpemUgICAgICAgICAgICAyNTZrOwoJcHJveHlfc2V0X2hlYWRlciAgICAgICAgICAgIEhvc3QgJGhvc3Q7CgoKICAgIHNlcnZlciB7CiAgICAgICAgbGlzdGVuIDgwODAgICAgIGRlZmF1bHRfc2VydmVyOwogICAgICAgIHNlcnZlcl9uYW1lICAgICAgICAgICAgICAgIF87CgogICAgICAgIHNlbmRmaWxlIG9mZjsKCiAgICAgICAgcm9vdCAgL3Zhci93d3cvaHRtbC92Z3NfYm9va2luZ19jb250cm9sL3B1YmxpYzsKICAgICAgICBpbmRleCBpbmRleC5waHAgaW5kZXguaHRtbDsKICAgICAgICBsb2NhdGlvbiAvIHsKICAgICAgICAgICAgIyBGaXJzdCBhdHRlbXB0IHRvIHNlcnZlIHJlcXVlc3QgYXMgZmlsZSwgdGhlbgogICAgICAgICAgICAjIGFzIGRpcmVjdG9yeSwgdGhlbiBmYWxsIGJhY2sgdG8gaW5kZXgucGhwCiAgICAgICAgICAgIHRyeV9maWxlcyAkdXJpICR1cmkvIC9pbmRleC5waHA/cT0kdXJpJiRhcmdzOwogICAgICAgIH0KCiAgICAgICAgIyByZWRpcmVjdCBzZXJ2ZXIgZXJyb3IgcGFnZXMgdG8gdGhlIHN0YXRpYyBwYWdlIC81MHguaHRtbAogICAgICAgICMKICAgICAgICBlcnJvcl9wYWdlIDUwMCA1MDIgNTAzIDUwNCAvNTB4Lmh0bWw7CiAgICAgICAgbG9jYXRpb24gPSAvNTB4Lmh0bWwgewogICAgICAgICAgICByb290IC92YXIvbGliL25naW54L2h0bWw7CiAgICAgICAgfQoKICAgICAgICAjIHBhc3MgdGhlIFBIUCBzY3JpcHRzIHRvIEZhc3RDR0kgc2VydmVyIGxpc3RlbmluZyBvbiAxMjcuMC4wLjE6OTAwMAogICAgICAgICMKICAgICAgICBsb2NhdGlvbiB+IFwucGhwJCB7CiAgICAgICAgICAgIHRyeV9maWxlcyAkdXJpID00MDQ7CiAgICAgICAgICAgIGZhc3RjZ2lfc3BsaXRfcGF0aF9pbmZvIF4oLitcLnBocCkoLy4rKSQ7CiAgICAgICAgICAgIGZhc3RjZ2lfcGFzcyAgMTI3LjAuMC4xOjkwMDA7CiAgICAgICAgICAgIGZhc3RjZ2lfcGFyYW0gU0NSSVBUX0ZJTEVOQU1FICRkb2N1bWVudF9yb290JGZhc3RjZ2lfc2NyaXB0X25hbWU7CiAgICAgICAgICAgIGZhc3RjZ2lfcGFyYW0gU0NSSVBUX05BTUUgJGZhc3RjZ2lfc2NyaXB0X25hbWU7CiAgICAgICAgICAgIGZhc3RjZ2lfaW5kZXggaW5kZXgucGhwOwogICAgICAgICAgICBpbmNsdWRlIGZhc3RjZ2lfcGFyYW1zOwogICAgICAgIH0KCiAgICAgICAgbG9jYXRpb24gfiogXC4oanBnfGpwZWd8Z2lmfHBuZ3xjc3N8anN8aWNvfHhtbCkkIHsKICAgICAgICAgICAgZXhwaXJlcyA1ZDsKICAgICAgICB9CgogICAgICAgICMgZGVueSBhY2Nlc3MgdG8gLiBmaWxlcywgZm9yIHNlY3VyaXR5CiAgICAgICAgIwogICAgICAgIGxvY2F0aW9uIH4gL1wuIHsKICAgICAgICAgICAgbG9nX25vdF9mb3VuZCBvZmY7CiAgICAgICAgICAgIGRlbnkgYWxsOwogICAgICAgIH0KCiAgICAgICAgIyBhbGxvdyBmcG0gcGluZyBhbmQgc3RhdHVzIGZyb20gbG9jYWxob3N0CiAgICAgICAgIwogICAgICAgIGxvY2F0aW9uIH4gXi8oZnBtLXN0YXR1c3xmcG0tcGluZykkIHsKICAgICAgICAgICAgYWNjZXNzX2xvZyBvZmY7CiAgICAgICAgICAgIGFsbG93IDEyNy4wLjAuMTsKICAgICAgICAgICAgZGVueSBhbGw7CiAgICAgICAgICAgIGZhc3RjZ2lfcGFyYW0gU0NSSVBUX0ZJTEVOQU1FICRkb2N1bWVudF9yb290JGZhc3RjZ2lfc2NyaXB0X25hbWU7CiAgICAgICAgICAgIGluY2x1ZGUgZmFzdGNnaV9wYXJhbXM7CiAgICAgICAgICAgIGZhc3RjZ2lfcGFzcyAxMjcuMC4wLjE6OTAwMDsKICAgICAgICB9CiAgICB9Cn0K' \
         > /root/nginx.conf.base64 && base64 -d /root/nginx.conf.base64 > /etc/nginx/nginx.conf && \
    echo "include = /etc/php7/php-fpm.d/*.conf" \
         > /etc/php7/php-fpm.conf && \
    echo "----COPY  fpm-pool.conf   /etc/php7/php-fpm.d/www.conf" && \
    echo $'W2dsb2JhbF0KZXJyb3JfbG9nID0gL2Rldi9zdGRlcnIKW3VwYW5oLXZoYW5kaWNhcC1jb21dCmxpc3RlbiA9IDEyNy4wLjAuMTo5MDAwCnVzZXIgPSBub2JvZHkKcG0uc3RhdHVzX3BhdGggPSAvZnBtLXN0YXR1cwpwbSA9IG9uZGVtYW5kCnBtLm1heF9jaGlsZHJlbiA9IDEwMApwbS5wcm9jZXNzX2lkbGVfdGltZW91dCA9IDMwczsKcG0ubWF4X3JlcXVlc3RzID0gMTAwMApjbGVhcl9lbnYgPSBubwpjYXRjaF93b3JrZXJzX291dHB1dCA9IHllcwpwaW5nLnBhdGggPSAvZnBtLXBpbmcK' \
         > /etc/php7/php-fpm.d/www.conf.base64 && base64 -d /etc/php7/php-fpm.d/www.conf.base64 > /etc/php7/php-fpm.d/www.conf && \
    echo $'bWVtb3J5X2xpbWl0ID0gNTEyTQp1cGxvYWRfbWF4X2ZpbGVzaXplID0gMjUwTQpwb3N0X21heF9zaXplICAgPSAyNTZNCgpbRGF0ZV0KZGF0ZS50aW1lem9uZT0iVVRDIgoK' \
         > /root/zzz_custom.ini.base64 && base64 -d /root/zzz_custom.ini.base64 > /etc/php7/conf.d/zzz_custom.ini && \
    echo '----COPY  supervisord.conf     /etc/supervisor/conf.d/supervisord.conf' && \
    echo $'W3N1cGVydmlzb3JkXQpub2RhZW1vbj10cnVlCmxvZ2ZpbGU9L2Rldi9udWxsCmxvZ2ZpbGVfbWF4Ynl0ZXM9MApwaWRmaWxlPS9ydW4vc3VwZXJ2aXNvcmQucGlkCgpbcHJvZ3JhbTpwaHAtZnBtXQpjb21tYW5kPXBocC1mcG03IC1GCnN0ZG91dF9sb2dmaWxlPS9kZXYvc3Rkb3V0CnN0ZG91dF9sb2dmaWxlX21heGJ5dGVzPTAKc3RkZXJyX2xvZ2ZpbGU9L2Rldi9zdGRlcnIKc3RkZXJyX2xvZ2ZpbGVfbWF4Ynl0ZXM9MAphdXRvcmVzdGFydD1mYWxzZQpzdGFydHJldHJpZXM9MAoKW3Byb2dyYW06bmdpbnhdCmNvbW1hbmQ9bmdpbnggLWcgJ2RhZW1vbiBvZmY7JwpzdGRvdXRfbG9nZmlsZT0vZGV2L3N0ZG91dApzdGRvdXRfbG9nZmlsZV9tYXhieXRlcz0wCnN0ZGVycl9sb2dmaWxlPS9kZXYvc3RkZXJyCnN0ZGVycl9sb2dmaWxlX21heGJ5dGVzPTAKYXV0b3Jlc3RhcnQ9ZmFsc2UKc3RhcnRyZXRyaWVzPTAK' \
         > /root/supervisord.conf.base64 && base64 -d /root/supervisord.conf.base64 > /etc/supervisor/conf.d/supervisord.conf

# Make sure files/folders needed by the processes are accessable when they run under the nobody user
RUN chown -R nobody.nobody /run && \
    chown -R nobody.nobody /var/lib/nginx && \
    chown -R nobody.nobody /var/tmp/nginx && \
    chown -R nobody.nobody /var/log/nginx && \
    chmod 644 /etc/supervisor/conf.d/supervisord.conf /etc/php7/php-fpm.d/www.conf  /etc/nginx/nginx.conf /etc/php7/conf.d/zzz_custom.ini

RUN echo $'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcGdJQkFBS0NBUUVBNGVrb3UxeXJhekJCSXJiUEMzNkxHSTZhb1dUTUFwdjY1WTAzV3Z4K3E0M1JKU21FCkxrazZkaWRCM0dhQTIvZUhSeDBkaWJIL0djaW93VHp2MGcwcmZJL3NNM1VicnRuL0k2QUZmSlNDejN0UUk0TlAKZElvMGFBRFRhM1EyVU84QndDYUgvUUdINGpMSTFOUi9RQTE5ckZIZlVXcktRRDlMRkFaQitybXl0Yy9OWk1rbwpMTmVrTHdXaUp5UkxmaXJvRzJHcG5hUmxBZStKUWE1c3ltVisvWWhqVDVsMk5taklrQk43ZHJPZitSNko0akFsCndtU1VQQVVkUEZXN21naGxENXlNVnZNUVVPUmtrRitxYkk4bDdpdTN4ZUgxeStjY3hIbHZ2ckd0bVZoMXpja2oKajlRYkR1bGhwazZnVzlXTHBsMlJjOWREdXQ5NXVsc2V4R3Y5RndJREFRQUJBb0lCQVFDU0hVL3UveDBRRXdITwpCaGNjQkJqTEpWRDJHaytwVUdHU255ZXlmYVVnS0hXaFo1ektveXBneVR0YjVpQnFKVXNsdjdzZkdEVTY1QUhpCkdodXk3RG00TXc0K3Fmdmh0N1hCd1BwTGZYS3Q1OEFKZUNDbjY4dkJpT2MxbE5DY3dEbU5vbDVLVWZjbFlsdHEKN0pYeFE4aUk3OXRVdVpGZXhKRTJ2bVZtV1QweFFhTE8xMFB2OTNyVHRPWTBUU1l6b0VGYTlUTEZqQkpnU2lIQQpCYmd4ZEgrQTZmN2NnR3g4a2RseDlxc09NRGxua3ZDd3hoTlB5aUtlenFNWHF2ZkovQ01iWHI0L3ZHelBjeFJWClJ2aExDSTBGNEJucGs2RzhROXM4bTMxTkg3THYyS3FrbXh4b0FZSVZNL0pzSElMTC81aUpOMVZFMVg0bkJKdm0Ka3pOcUxSemhBb0dCQVB4MWUyOVlVY3hhTG9BRDIydmlhQk9QSjU1MUlrT2hxM3ExZU56TXZBd3A1UFFwSWsyTApYZGVTNXpFZkN3aDBTNHVJd0VscjR3d0xZellVQUpGaXpzVE40TG9MamhIMFVnUXEwd0EwZHArNHpFbStIYUo4CmxhWVdLSnhFV2V4QTJhOXNhMjFOTVd0OENsUllEWDNTblVhNHNUd1BLWFBsV2NRSmRNVjNwMkxOQW9HQkFPVVUKV1YrWWtSVndUQjR4WDErWGVHVHJYbW90cVRHbi9Mc1J6aEc1SDBLZmwrKzZIMFJTb3FQYXN2enZpdm9WZEdvTAo1ZDcxdUo4UHkxN1NQdjNJcDhkbE5kVW5nUW1ZZ2dYbVJDNmRwbWNOOE1PbzEzWnBaaVZLWWZkeDlEbU91MWo4CmVQcmZySFVGNWZ6T09ZSDB4NnFtNUVTYVJMVWN5NVNmdXFLb293ZHpBb0dCQUl5cFhKditScDBvaGc0WG1CTDEKTSszcDdqWXdwMld0VjJEb2FhNEVlS1lDVmFuZ25WYzlWb3o5TWNsQnRhRUJRdkk4d0g1b0dUb2x3aUpvWktTYwp1LzRWZzZmRk5tUTBqOW40amxYbjVVdzY1OEFTcUdwWEpmNURERjk5Q2VsRGZNWnNEekw0TnBmZnBkVzJ0ZFdzCkdxdER6cVJiQWtxcnVDY3M2WjM0ZkEvbEFvR0JBSk1pNU55Lzg4QWZadVNsdGFxQ2NiUHdjYTRsTWQxUkZzVloKQkZEaDVMQTRMYkN1alZLbStRdmhkc0Y3WW5xS3VVRTc3eU9zRkM4bVIrdlpndGdpdjVFVTh1UzhBT2VXNnp5Ngp6K1JaSWY1ak45ZVVaUUFMWnE1Zy9sZWUrOHpVWG9VamROaytQVmpVdHdvUHMyUkRRdFBiYWhhZU42OVVsWFlhCnVoZXIxVHI5QW9HQkFMSTVGM1p0ZzNHUGtuZTJXOFZ3MDNVZ2JrS3BnRS9qNyt1UW5QZ3hENCtRTnBpN1FRMFkKaUEvS2o3amM3NzhDUzY0dXh2U2RmbnV6aDZJc2REVS9OUXZzZHJnNExBSnIxaStTZDIrNjZUZjJrU2wvd3ZxRQpVZmlaNzNkWFpPa3UwK0VVN1Mwb293cmsvY2Q5bXZaanlWUE4ycjVKZG85QVc3RTdoN29oREcyWAotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=' \
    > /root/.ssh/id_rsa.base64 && base64 -d /root/.ssh/id_rsa.base64 > /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa && \
    ssh-keyscan github.com > /root/.ssh/known_hosts && \
    cd /var/www/html/ && \
    git init && \
    git clone --depth=1 -b master -v git@github.com:vgsholding/vgs_booking_control.git

WORKDIR /var/www/html/vgs_booking_control/
RUN composer install
RUN npm install 
RUN npm install pm2
RUN npm run prod
RUN chown nobody:nobody -R /var/www/html/vgs_booking_control/storage/ 

ARG 2020.05.21
RUN git checkout . &&  git  pull -v  && npm  install && npm run prod
USER nobody
# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
